---

# prepare ubuntu 16.10 vm for ansible
- hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: install python
      raw: apt-get update && apt-get install -y python python-dev python-setuptools aptitude

# common roles for all nodes
- hosts: all
  become: yes
  roles:
    - role: common

# individual roles per hostgroup
- hosts: db
  roles:
    - role: mongodb
      become: yes

- hosts: jupyterhub
  roles:
    - role: jupyterhub
      become: yes
    - role: user
      become: yes
